## Preprocessing

In [4]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [5]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN','NAME'])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [6]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [7]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ['T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: count, dtype: int64

In [9]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [10]:
# You may find it helpful to look at CLASSIFICATION value counts >1
value_counts = application_df['CLASSIFICATION'].value_counts()
print(value_counts[value_counts > 1])

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [11]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = value_counts[value_counts < 1883].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [12]:
# Convert categorical data to numeric with `pd.get_dummies`
categorical_data = [
    'APPLICATION_TYPE',
    'AFFILIATION',
    'CLASSIFICATION',
    'USE_CASE',
    'ORGANIZATION',
    'INCOME_AMT',
    'SPECIAL_CONSIDERATIONS'
]
application_df_categories = pd.get_dummies(application_df, columns=categorical_data)
application_df_categories.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [13]:
# Split our preprocessed data into our features and target arrays
y = application_df_categories['IS_SUCCESSFUL']
X = application_df_categories.drop(columns='IS_SUCCESSFUL')

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [14]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [15]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn = tf.keras.models.Sequential()
# Input layer
nn.add(tf.keras.layers.Dense(units=64, activation='relu', input_dim = X_train_scaled.shape[1]))

# First hidden layer
nn.add(tf.keras.layers.Dense(units=32, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=16, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

# Check the structure of the model
nn.summary()

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │         2,880 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,505 (21.50 KB)

 Trainable params: 5,505 (21.50 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
# Compile the model
nn.compile(optimizer='adam',
           loss='binary_crossentropy',
           metrics=['accuracy'])

In [17]:
# Train the model
fit_model = nn.fit(
    X_train_scaled, y_train,
    epochs=100,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 760us/step - accuracy: 0.7058 - loss: 0.5948 - val_accuracy: 0.7296 - val_loss: 0.5603
Epoch 2/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step - accuracy: 0.7263 - loss: 0.5598 - val_accuracy: 0.7320 - val_loss: 0.5494
Epoch 3/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 628us/step - accuracy: 0.7283 - loss: 0.5573 - val_accuracy: 0.7351 - val_loss: 0.5508
Epoch 4/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 638us/step - accuracy: 0.7346 - loss: 0.5446 - val_accuracy: 0.7329 - val_loss: 0.5477
Epoch 5/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 621us/step - accuracy: 0.7280 - loss: 0.5505 - val_accuracy: 0.7368 - val_loss: 0.5484
Epoch 6/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 648us/step - accuracy: 0.7319 - loss: 0.5481 - val_accuracy: 0.7372 - val_loss: 0.5499
Epoch 7/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - accuracy: 0.7328 - loss: 0.5473 - val_accuracy: 0.7370 - val_loss: 0.5499
Epoch 8/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 609us/step - accuracy: 0.7306 - loss: 0.5505 - val_accuracy: 0.7370 - val_loss: 0.5471
Epoch 9/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 615us/step - accuracy: 0.7271 - loss: 0.5521 - val_accuracy: 0.7374 - val_loss: 0.5482
Epoch 10/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 611us/step - accuracy: 0.7354 - loss: 0.5471 - val_accuracy: 0.7351 - val_loss: 0.5504
Epoch 11/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 602us/step - accuracy: 0.7296 - loss: 0.5485 - val_accuracy: 0.7362 - val_loss: 0.5520
Epoch 12/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 614us/step - accuracy: 0.7406 - loss: 0.5415 - val_accuracy: 0.7353 - val_loss: 0.5495
Epoch 13/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 639us/step - accuracy: 0.7362 - loss: 0.5439 - val_accuracy: 0.7372 - val_loss: 0.5476
Epoch 14/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - accuracy: 0.7345 - loss: 0.5431 - val_accuracy: 0.7380 - val_loss: 0.5504
Epoch 15/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 610us/step - accuracy: 0.7362 - loss: 0.5401 - val_accuracy: 0.7380 - val_loss: 0.5484
Epoch 16/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 607us/step - accuracy: 0.7383 - loss: 0.5413 - val_accuracy: 0.7376 - val_loss: 0.5497
Epoch 17/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 607us/step - accuracy: 0.7327 - loss: 0.5471 - val_accuracy: 0.7382 - val_loss: 0.5496
Epoch 18/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 618us/step - accuracy: 0.7338 - loss: 0.5393 - val_accuracy: 0.7378 - val_loss: 0.5498
Epoch 19/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 610us/step - accuracy: 0.7334 - loss: 0.5446 - val_accuracy: 0.7349 - val_loss: 0.5525
Epoch 20/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 648us/step - accuracy: 0.7356 - loss: 0.5432 - val_accuracy: 0.7353 - val_loss: 0.5499
Epoch 21/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 613us/step - accuracy: 0.7314 - loss: 0.5464 - val_accuracy: 0.7370 - val_loss: 0.5474
Epoch 22/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 606us/step - accuracy: 0.7357 - loss: 0.5414 - val_accuracy: 0.7359 - val_loss: 0.5500
Epoch 23/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - accuracy: 0.7367 - loss: 0.5402 - val_accuracy: 0.7318 - val_loss: 0.5507
Epoch 24/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 603us/step - accuracy: 0.7366 - loss: 0.5460 - val_accuracy: 0.7329 - val_loss: 0.5517
Epoch 25/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 625us/step - accuracy: 0.7360 - loss: 0.5425 - val_accuracy: 0.7382 - val_loss: 0.5520
Epoch 26/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 612us/step - accuracy: 0.7336 - loss: 0.5428 - val_accuracy: 0.7382 - val_loss: 0.5525
Epoch 27/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 654us/step - accuracy: 0.7385 - loss: 0.5371 - val_accuracy: 0.7368 - val_loss: 0.5530
Epoch 28/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 611us/step - accuracy: 0.7361 - loss: 0.5398 - val_accuracy: 0.7386 - val_loss: 0.5509
Epoch 29/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step - accuracy: 0.7440 - loss: 0.5307 - val_accuracy: 0.7368 - val_loss: 0.5524
Epoch 30/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 618us/step - accuracy: 0.7357 - loss: 0.5420 - val_accuracy: 0.7361 - val_loss: 0.5557
Epoch 31/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step - accuracy: 0.7340 - loss: 0.5419 - val_accuracy: 0.7368 - val_loss: 0.5532
Epoch 32/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 612us/step - accuracy: 0.7355 - loss: 0.5418 - val_accuracy: 0.7376 - val_loss: 0.5577
Epoch 33/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 650us/step - accuracy: 0.7374 - loss: 0.5420 - val_accuracy: 0.7349 - val_loss: 0.5554
Epoch 34/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 612us/step - accuracy: 0.7367 - loss: 0.5401 - val_accuracy: 0.7366 - val_loss: 0.5565
Epoch 35/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 615us/step - accuracy: 0.7362 - loss: 0.5435 - val_accuracy: 0.7368 - val_loss: 0.5534
Epoch 36/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 614us/step - accuracy: 0.7388 - loss: 0.5388 - val_accuracy: 0.7372 - val_loss: 0.5506
Epoch 37/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step - accuracy: 0.7370 - loss: 0.5368 - val_accuracy: 0.7378 - val_loss: 0.5520
Epoch 38/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - accuracy: 0.7433 - loss: 0.5337 - val_accuracy: 0.7353 - val_loss: 0.5532
Epoch 39/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 640us/step - accuracy: 0.7372 - loss: 0.5414 - val_accuracy: 0.7364 - val_loss: 0.5564
Epoch 40/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step - accuracy: 0.7435 - loss: 0.5349 - val_accuracy: 0.7345 - val_loss: 0.5574
Epoch 41/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 621us/step - accuracy: 0.7438 - loss: 0.5369 - val_accuracy: 0.7380 - val_loss: 0.5563
Epoch 42/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 612us/step - accuracy: 0.7342 - loss: 0.5429 - val_accuracy: 0.7359 - val_loss: 0.5504
Epoch 43/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 620us/step - accuracy: 0.7336 - loss: 0.5401 - val_accuracy: 0.7351 - val_loss: 0.5612
Epoch 44/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step - accuracy: 0.7400 - loss: 0.5375 - val_accuracy: 0.7370 - val_loss: 0.5601
Epoch 45/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 659us/step - accuracy: 0.7384 - loss: 0.5338 - val_accuracy: 0.7378 - val_loss: 0.5544
Epoch 46/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step - accuracy: 0.7329 - loss: 0.5425 - val_accuracy: 0.7370 - val_loss: 0.5590
Epoch 47/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 614us/step - accuracy: 0.7407 - loss: 0.5341 - val_accuracy: 0.7359 - val_loss: 0.5578
Epoch 48/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step - accuracy: 0.7405 - loss: 0.5367 - val_accuracy: 0.7366 - val_loss: 0.5619
Epoch 49/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 624us/step - accuracy: 0.7426 - loss: 0.5339 - val_accuracy: 0.7362 - val_loss: 0.5569
Epoch 50/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - accuracy: 0.7404 - loss: 0.5348 - val_accuracy: 0.7374 - val_loss: 0.5557
Epoch 51/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 655us/step - accuracy: 0.7380 - loss: 0.5362 - val_accuracy: 0.7374 - val_loss: 0.5600
Epoch 52/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 619us/step - accuracy: 0.7461 - loss: 0.5274 - val_accuracy: 0.7366 - val_loss: 0.5589
Epoch 53/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - accuracy: 0.7411 - loss: 0.5353 - val_accuracy: 0.7355 - val_loss: 0.5635
Epoch 54/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 612us/step - accuracy: 0.7404 - loss: 0.5348 - val_accuracy: 0.7347 - val_loss: 0.5599
Epoch 55/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 620us/step - accuracy: 0.7360 - loss: 0.5377 - val_accuracy: 0.7328 - val_loss: 0.5633
Epoch 56/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 612us/step - accuracy: 0.7378 - loss: 0.5362 - val_accuracy: 0.7353 - val_loss: 0.5619
Epoch 57/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 649us/step - accuracy: 0.7415 - loss: 0.5328 - val_accuracy: 0.7364 - val_loss: 0.5619
Epoch 58/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 618us/step - accuracy: 0.7429 - loss: 0.5317 - val_accuracy: 0.7372 - val_loss: 0.5633
Epoch 59/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step - accuracy: 0.7404 - loss: 0.5376 - val_accuracy: 0.7337 - val_loss: 0.5664
Epoch 60/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 613us/step - accuracy: 0.7402 - loss: 0.5351 - val_accuracy: 0.7374 - val_loss: 0.5606
Epoch 61/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - accuracy: 0.7402 - loss: 0.5339 - val_accuracy: 0.7370 - val_loss: 0.5611
Epoch 62/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 613us/step - accuracy: 0.7395 - loss: 0.5348 - val_accuracy: 0.7361 - val_loss: 0.5615
Epoch 63/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 618us/step - accuracy: 0.7410 - loss: 0.5326 - val_accuracy: 0.7353 - val_loss: 0.5681
Epoch 64/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 627us/step - accuracy: 0.7450 - loss: 0.5287 - val_accuracy: 0.7364 - val_loss: 0.5609
Epoch 65/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 623us/step - accuracy: 0.7398 - loss: 0.5348 - val_accuracy: 0.7359 - val_loss: 0.5717
Epoch 66/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step - accuracy: 0.7373 - loss: 0.5358 - val_accuracy: 0.7351 - val_loss: 0.5696
Epoch 67/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 621us/step - accuracy: 0.7363 - loss: 0.5363 - val_accuracy: 0.7361 - val_loss: 0.5646
Epoch 68/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 658us/step - accuracy: 0.7400 - loss: 0.5344 - val_accuracy: 0.7368 - val_loss: 0.5695
Epoch 69/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 610us/step - accuracy: 0.7476 - loss: 0.5265 - val_accuracy: 0.7366 - val_loss: 0.5623
Epoch 70/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - accuracy: 0.7411 - loss: 0.5364 - val_accuracy: 0.7380 - val_loss: 0.5638
Epoch 71/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 615us/step - accuracy: 0.7446 - loss: 0.5320 - val_accuracy: 0.7324 - val_loss: 0.5623
Epoch 72/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 615us/step - accuracy: 0.7339 - loss: 0.5358 - val_accuracy: 0.7376 - val_loss: 0.5663
Epoch 73/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 618us/step - accuracy: 0.7383 - loss: 0.5343 - val_accuracy: 0.7361 - val_loss: 0.5618
Epoch 74/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 649us/step - accuracy: 0.7403 - loss: 0.5331 - val_accuracy: 0.7376 - val_loss: 0.5683
Epoch 75/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 612us/step - accuracy: 0.7371 - loss: 0.5406 - val_accuracy: 0.7361 - val_loss: 0.5640
Epoch 76/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 620us/step - accuracy: 0.7408 - loss: 0.5327 - val_accuracy: 0.7362 - val_loss: 0.5655
Epoch 77/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 619us/step - accuracy: 0.7433 - loss: 0.5317 - val_accuracy: 0.7376 - val_loss: 0.5649
Epoch 78/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 647us/step - accuracy: 0.7372 - loss: 0.5356 - val_accuracy: 0.7370 - val_loss: 0.5653
Epoch 79/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 714us/step - accuracy: 0.7439 - loss: 0.5288 - val_accuracy: 0.7368 - val_loss: 0.5657
Epoch 80/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - accuracy: 0.7423 - loss: 0.5334 - val_accuracy: 0.7366 - val_loss: 0.5776
Epoch 81/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step - accuracy: 0.7382 - loss: 0.5326 - val_accuracy: 0.7357 - val_loss: 0.5637
Epoch 82/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step - accuracy: 0.7414 - loss: 0.5335 - val_accuracy: 0.7376 - val_loss: 0.5642
Epoch 83/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 621us/step - accuracy: 0.7386 - loss: 0.5358 - val_accuracy: 0.7368 - val_loss: 0.5604
Epoch 84/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 652us/step - accuracy: 0.7344 - loss: 0.5389 - val_accuracy: 0.7359 - val_loss: 0.5727
Epoch 85/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 623us/step - accuracy: 0.7365 - loss: 0.5362 - val_accuracy: 0.7361 - val_loss: 0.5778
Epoch 86/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - accuracy: 0.7469 - loss: 0.5274 - val_accuracy: 0.7368 - val_loss: 0.5654
Epoch 87/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 612us/step - accuracy: 0.7413 - loss: 0.5308 - val_accuracy: 0.7372 - val_loss: 0.5676
Epoch 88/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 623us/step - accuracy: 0.7422 - loss: 0.5320 - val_accuracy: 0.7364 - val_loss: 0.5657
Epoch 89/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 647us/step - accuracy: 0.7406 - loss: 0.5354 - val_accuracy: 0.7366 - val_loss: 0.5617
Epoch 90/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 615us/step - accuracy: 0.7416 - loss: 0.5324 - val_accuracy: 0.7343 - val_loss: 0.5806
Epoch 91/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 618us/step - accuracy: 0.7434 - loss: 0.5324 - val_accuracy: 0.7341 - val_loss: 0.5714
Epoch 92/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - accuracy: 0.7419 - loss: 0.5318 - val_accuracy: 0.7353 - val_loss: 0.5788
Epoch 93/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 773us/step - accuracy: 0.7406 - loss: 0.5356 - val_accuracy: 0.7368 - val_loss: 0.5678
Epoch 94/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 982us/step - accuracy: 0.7458 - loss: 0.5256 - val_accuracy: 0.7376 - val_loss: 0.5675
Epoch 95/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 620us/step - accuracy: 0.7361 - loss: 0.5341 - val_accuracy: 0.7372 - val_loss: 0.5650
Epoch 96/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 610us/step - accuracy: 0.7390 - loss: 0.5320 - val_accuracy: 0.7378 - val_loss: 0.5660
Epoch 97/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 726us/step - accuracy: 0.7409 - loss: 0.5341 - val_accuracy: 0.7368 - val_loss: 0.5645
Epoch 98/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 611us/step - accuracy: 0.7349 - loss: 0.5359 - val_accuracy: 0.7368 - val_loss: 0.5606
Epoch 99/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 650us/step - accuracy: 0.7422 - loss: 0.5334 - val_accuracy: 0.7362 - val_loss: 0.5642
Epoch 100/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 0s 611us/step - accuracy: 0.7422 - loss: 0.5322 - val_accuracy: 0.7351 - val_loss: 0.5702

In [18]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 423us/step - accuracy: 0.7277 - loss: 0.5615
Loss: 0.5614854097366333, Accuracy: 0.7276967763900757

In [19]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.